### ISSUE TITLE
Don't include HTTP resources on HTTPS pages

### ISSUE THREAD

**Issue by hardfalcon** [OParl/dev-website#17]
[https://oparl.org/presse-berichte/](https://oparl.org/presse-berichte/) references/includes pictures from wordpress.com via unencrypted HTTP although wordpress.com offers HTTPS.

**Comment by the-infinity** [comment]
Huh. wordpress.com finally fixed it.
There are still some unencrypted images because of OG tags, which is because the news sites where the OG tags come from do not support https. Can't be done a lot against this (without running in legal problems by copying images to the own server).

**Comment by eFrane** [comment]
Since the remaining non-https references are external and cannot be changed
    this issue will be closed.
