### ISSUE TITLE
Schema URLs for embedded objects show parent objects instead

### ISSUE THREAD

**Issue by konstin** [OParl/dev-website#18]
E.g. https://schema.oparl.org/1.0/Consultation shows the schema for Paper

**Comment by eFrane** [comment]
Due to embedded entities being embedded in the entity description of their respective parent
in OParl 1.0, this is intended behaviour.

**Comment by akuckartz** [comment]
I think that this is surprising. What is the motivation for this behavior?

**Comment by eFrane** [comment]
This is fixed now.
