### ISSUE TITLE
Create overview page for available reference/demo endpoints

### ISSUE THREAD

**Issue by eFrane** [OParl/dev-website#46]
Should be located at /api/oparl/ and behave in the same "deliver html
over web, json over non-web"-way as the OParl API itself.

**Comment by eFrane** [comment]
This exists as https://dev.oparl.org/endpunkte for the HTML version and https://dev.oparl.org/api/endpoints

**Comment by akuckartz** [comment]
Does the solution use content negotiation as indicated by "deliver html over web, json over non-web" ?

**Comment by eFrane** [comment]
Nope, but the web version will link to the api version in a future update. There is still some unfinished business on this end but I felt that the core of this issue is done as the data is available.
